### ISSUE TITLE
Launcher Error: `this._browserFactory.defaultBrowser is undefined` after system-wide install

### ISSUE THREAD

**Issue by goekce** [deathbeds/ipydrawio#121]
## Description

When I click on `Diagram` on the launcher window in Jupyterlab, a window pops up with:
```
Launcher Error
this._browserFactory.defaultBrowser is undefined
```

## Reproduce

1. Install `ipydrawio` system-wide using the wheel from pypi.org
2. Restart Jupyterlab
3. click on `Diagram` on the launcher window
4. Above error pops up and ipydrawio tab does not open up. Moreover `jupyter labextension list` warns that ipydrawio is outdated.

## Expected behavior

I should see a new ipydrawio tab

## Context

- Operating System and version: ArchLinux
- Browser and version: Firefox 120
- JupyterLab version: 4.0.9
- `ipydrawio-*` version(s): 1.3.0

<details><summary>Required: installed server extensions</summary>
<pre>
Config dir: /home/u/.jupyter

Config dir: /usr/etc/jupyter

Config dir: /usr/local/etc/jupyter
</pre>
</details>

<details><summary>Required: installed lab extensions</summary>
<pre>
JupyterLab v4.0.9
/usr/share/jupyter/labextensions
        ipycanvas v0.13.1 enabled OK
        jupyterlab_pygments v0.3.0 enabled OK (python, jupyterlab_pygments)
        nbgrader v0.9.1 enabled OK (python, nbgrader)
        @jupyter-widgets/jupyterlab-manager v5.0.9 enabled OK (python, jupyterlab_widgets)
        @jupyter-notebook/lab-extension v7.0.6 enabled OK
        @jupyter-lsp/jupyterlab-lsp v5.0.1 enabled OK (python, jupyterlab-lsp)
        @deathbeds/ipydrawio v1.3.0 enabled  X (python, ipydrawio)
        @deathbeds/ipydrawio-jupyter-templates v1.3.0 enabled  X (python, ipydrawio)
        @deathbeds/ipydrawio-notebook v1.3.0 enabled  X (python, ipydrawio)
        @deathbeds/ipydrawio-webpack v21.1.600 enabled  X (python, ipydrawio)

   The following extensions are outdated:
        @deathbeds/ipydrawio
        @deathbeds/ipydrawio-jupyter-templates
        @deathbeds/ipydrawio-notebook
        @deathbeds/ipydrawio-webpack
        
   Consider checking if an update is available for these packages.

Disabled extensions:
    @jupyterlab/completer-extension:base-service
    @jupyterlab/fileeditor-extension:language-server
    @jupyterlab/lsp-extension:settings
    @jupyterlab/notebook-extension:language-server

</pre>
</details>

<details><summary>Browser Output (recommended for all interface issues)</summary>
<pre>
TypeError: this._browserFactory.defaultBrowser is undefined
    execute https://server.com/user/u/lab/extensions/@deathbeds/ipydrawio/static/883.c7be8e586f06056e66c4.js?v=c7be8e586f06056e66c4:1
    execute https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    g https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    Ue https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    Qe https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    je https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    al https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    ul https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    dl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    Os https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    De https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    dl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    lt https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    tt https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    fl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    ol https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    cl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    cl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    createRoot https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    renderDOM https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    renderDOM https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    onUpdateRequest https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    processMessage https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    b https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    o https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    onAfterAttach https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    processMessage https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    b https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    o https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    onAfterAttach https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    processParentMessage https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    notifyLayout https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    processMessage https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    b https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    o https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    attachWidget https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    addWidget https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    addWidget https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    _addToMainArea https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    add https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    execute https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    execute https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    a https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    m https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    l https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    emit https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    d https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    d https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    d https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    route https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    activate https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    promise callback*activate https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    promise https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    promise callback*activatePlugin https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    resolveRequiredService https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    n https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    activatePlugin https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    resolveRequiredService https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    n https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    activatePlugin https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    resolveOptionalService https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    i https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    activatePlugin https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    i https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    start https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    K https://server.com/user/u/static/lab/812.fa595a2be03628e77c9a.js?v=fa595a2be03628e77c9a:1
    e https://server.com/user/u/static/lab/main.8d5c7fc83ea3808d9641.js?v=8d5c7fc83ea3808d9641:1
    37559 https://server.com/user/u/static/lab/main.8d5c7fc83ea3808d9641.js?v=8d5c7fc83ea3808d9641:1
    t https://server.com/user/u/static/lab/main.8d5c7fc83ea3808d9641.js?v=8d5c7fc83ea3808d9641:1
    <anonymous> https://server.com/user/u/static/lab/main.8d5c7fc83ea3808d9641.js?v=8d5c7fc83ea3808d9641:1
    <anonymous> https://server.com/user/u/static/lab/main.8d5c7fc83ea3808d9641.js?v=8d5c7fc83ea3808d9641:1
jlab_core.a61821d8a2a9c35d7996.js:1:837202
    g https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    (Async: promise callback)
    g https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    Ue https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    Qe https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    je https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    al https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    ul https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    dl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    Os https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    De https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    dl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    lt https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    tt https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    (Async: EventListener.handleEvent)
    fl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    ol https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    cl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    cl https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    createRoot https://server.com/user/u/static/lab/3935.905285b8e22c337968ed.js?v=905285b8e22c337968ed:2
    renderDOM https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    renderDOM https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    onUpdateRequest https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    processMessage https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    b https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    o https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    onAfterAttach https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    processMessage https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    b https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    o https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    onAfterAttach https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    processParentMessage https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    notifyLayout https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    processMessage https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    b https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    o https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    attachWidget https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    addWidget https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    addWidget https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    _addToMainArea https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    add https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    execute https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    execute https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1
    a https://server.com/user/u/static/lab/jlab_core.a61821d8a2a9c35d7996.js?v=a61821d8a2a9c35d7996:1

8 min

</pre>
</details>

# Additional remarks

- Installation in a virtualenv works.
- Instead of using the wheel, I can try building the wheel myself. However I could not find any instructions how to build from source.

**Comment by bollwyvl** [comment]
please see: https://github.com/deathbeds/ipydrawio/issues/119

**Comment by goekce** [comment]
Did not notice that pip installed the version 3 of Jupyterlab. Sorry @bollwyvl 🙁
