### ISSUE TITLE
.ipynb now open with ipydrawio rather than with notebook editor

### ISSUE THREAD

**Issue by krassowski** [deathbeds/ipydrawio#21]
## Description

Since fresh JupyterLab 3.0.12 notebooks now open with ipydrawio instead with notebook editor on clicking in the file browser, on jump-to-definition with LSP, and in jupyterlab-git panel. This is very likely due to this fix in filetype registry matching: https://github.com/jupyterlab/jupyterlab/pull/9958

## Reproduce

1. Install 3.0.12 and ipydrawio
2. Open an existing notebook from file browser
3. See diagram notebook opening instead of the notebook editor

![diagram-notebook](https://user-images.githubusercontent.com/5832902/112721785-c6510280-8efd-11eb-9a9a-c7e58bf0cd47.png)

## Expected behavior

The priority of diagram notebook is lower than of notebook.

**Comment by bollwyvl** [comment]
Thanks, I'll fix this.
