### ISSUE TITLE
The tools opens up intead of Jupyter notebook, JupyterLab 3.0.9

### ISSUE THREAD

**Issue by soerendip** [deathbeds/ipydrawio#38]
I now repeatedly face the issue that I click on a notebook file `.pynb` ending and instead, the drawer.io plugin opens and I am not able to see the notebook content. Using JupyterLab 3.0.9. Unfortunately, the About page does not tell me what version it is. It is a bit scary to lose all my notebooks to the app. I guess that is critical.

**Comment by soerendip** [comment]
![image](https://user-images.githubusercontent.com/3391614/116004031-22bb4680-a5be-11eb-92f3-1ca0a53ad363.png)

**Comment by soerendip** [comment]
I am not sure how to reproduce it. I restarted the JupyterLab server and that let me access the original notebook. I leave it open in case other people experience the same issue.

**Comment by bollwyvl** [comment]
What version of `ipydrawio` do you have installed? 

It might be just as well to drop `jupyter troubleshoot` and `pip freeze` or `conda list --explicit` depending on your method.

**Comment by krassowski** [comment]
Recollecting https://github.com/deathbeds/ipydrawio/issues/21 I belive it would be suficient to upgrade JupyterLab to 3.0.12 (and `ipydrawio` to latest stable)

**Comment by soerendip** [comment]
I updated `jupyter` and `ipydrawio`. And reloaded the notebook. It seems to be working again now. 

```
pip freeze |grep drawio
> ipydrawio==1.0.1

conda env export | jupyter
>
  - jupyter-packaging=0.9.2=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39hf3d152e_0
  - jupyter_server=1.6.4=py39hf3d152e_0
  - jupyterlab=3.0.14=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.5.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
    - jupyter-dash==0.4.0
```

**Comment by soerendip** [comment]
Thank you.
